# Generated by Django 3.2.11 on 2022-01-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.IntegerField()),
                ('container_no', models.IntegerField()),
                ('container_quantity', models.IntegerField()),
                ('container_price', models.IntegerField()),
                ('container_on_hand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_lastname', models.CharField(max_length=100)),
                ('customer_age', models.IntegerField()),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_contact', models.IntegerField()),
                ('customer_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_lastname', models.CharField(max_length=100)),
                ('employee_age', models.IntegerField()),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_total', models.IntegerField()),
                ('payment_transaction_id', models.IntegerField()),
                ('payment_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.customer')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_quantity', models.IntegerField()),
                ('transaction_total', models.IntegerField()),
                ('transaction_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.customer')),
                ('transaction_payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.payment')),
                ('transaction_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.product')),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('delivery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_transaction_id', models.IntegerField()),
                ('delivery_quantity', models.IntegerField()),
                ('delivery_delivery_man', models.CharField(max_length=20)),
                ('delivery_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.customer')),
                ('delivery_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.product')),
            ],
        ),
    ]
