# Generated by Django 2.0.7 on 2022-01-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
