# Generated by Django 3.2.11 on 2022-01-12 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0003_alter_container_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.customer')),
                ('cart_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_payment_id',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
