# Generated by Django 3.2.11 on 2022-01-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0004_auto_20220112_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_customer_id',
            field=models.IntegerField(),
        ),
    ]
