# Generated by Django 2.0.7 on 2022-01-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0006_alter_cart_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_product_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
