# Generated by Django 2.0.7 on 2022-01-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0007_auto_20220115_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_age',
        ),
    ]
