# Generated by Django 2.0.7 on 2022-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0008_remove_customer_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_lastname',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_city',
            field=models.CharField(default='bangalore', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(default='bit@mail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_zipcode',
            field=models.IntegerField(default=800001),
            preserve_default=False,
        ),
    ]
