# Generated by Django 2.0.7 on 2022-01-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0009_auto_20220115_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_zipcode',
            field=models.BigIntegerField(),
        ),
    ]
