# Generated by Django 2.0.7 on 2022-01-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0010_auto_20220115_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(default=0)),
                ('order_quantity', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.customer')),
                ('order_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.product')),
            ],
        ),
    ]
