# Generated by Django 2.0.7 on 2022-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0012_auto_20220115_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_product_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_quantity',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
