# Generated by Django 2.0.7 on 2022-01-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0013_auto_20220115_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_product_id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_selling.transaction'),
        ),
    ]
