# Generated by Django 2.0.7 on 2022-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0014_auto_20220115_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(default='home', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_city',
            field=models.CharField(default='home', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_contact',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_zipcode',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
