# Generated by Django 2.0.7 on 2022-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_selling', '0015_auto_20220115_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_salary',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
